# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:                    # Global permissions configuration starts here
  contents: write                # 'read' access to repository contents
  pull-requests: write   
  id-token: write

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22]
    name: Test on Node.js ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: authentification
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: npm ci

      - name: Test
        run: |
              if [ -f package.json ] && grep -q '"test":' package.json; then
                npm test
              else
                echo "No tests configured"
              fi

  release:
    needs: test
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
     
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22


      - name: Synchroniser resume.json
        run: git checkout origin/main -- resume.json

      - name: Install
        run: npm install

      - name: shown npm
        run: npm ls        

      - name: Install resume
        run: npx resumed render resume.json --theme jsonresume-theme-stackoverflowmar

      - name: create index
        run: mv resume.html index.html

      - name: Convert pdf
        run: npm run start || echo "No start script found"        

      - name: Display event name 
        run: echo "github.event_name=${{ github.event_name }}"
    
      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      
  deploy-coverage:
    if: github.ref == 'refs/heads/main'
    needs: release

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

          
          
     
